version: '2'
services:
    # Web Server / Nginx
    web:
        image: nginx:1.13.9-alpine
        container_name: web
        working_dir: /var/www
        restart: always
        volumes_from:
            - php-fpm
        depends_on:
            - php-fpm
        ports:
            - "80:80"
            - "443:443"
            - "5000:5000"
    # Application / PHP-FPM
    php-fpm:
        build: .
        # image: gctcntgc/talentcloud
        container_name: php-fpm
        working_dir: /var/www
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./etc/ssl:/etc/ssl"
            - "/var/www/vendor"
            - "./:/var/www"
        ports:
            - "9000:9000"
