version: '2'
services:
    web:
        image: nginx:stable-alpine
        container_name: web
        env_file: .env
        restart: always
        ports:
            - "5000:5000"
        volumes_from:
            - app
        depends_on:
            - app
    app:
        # image: gctcntgc/talentcloud
        build: .
        container_name: app
        restart: always
        working_dir: /var/www
        ports:
            - "9000:9000"
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./vendor:/var/www/vendor"
            - "./etc/ssl:/etc/ssl"
            - "./:/var/www"
